version: "2"
linters:
  enable:
    - gosec
    - revive
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
