name: update shukujitsu.yml

on:
  schedule:
    # 毎週月曜 02:00 UTC に実行
    - cron: '0 2 * * MON'

jobs:
  update_shukujitsu:
    timeout-minutes: 5

    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: auto update shukujitsu.yml by google calendar api
        run: |
          go run ./auto_update_holiday_dataset/main.go
        env:
          GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Automated Change
          file_pattern: shukujitsu.yml
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: auto-commit-action で変更を検知した場合に Slack 通知する。
      #       どの程度頻度があるか把握する上で通知設定をしている。
      - name: Slack Notification on Success
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MSG_AUTHOR: ' '
          SLACK_TITLE: '`shukujitsu.yml`'
          SLACK_MESSAGE: ':smile: Successfully auto commit <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>'
          MSG_MINIMAL: true
          SLACK_FOOTER: 'by <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|/actions/runs/${{ github.run_id }}>'
