name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pick golang_version
        id: golang
        run: echo ::set-output name=version::$(awk '{print $2}' .tool-versions)

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.golang.outputs.version }}

      - run: go test -v -count=1 -race -cover -coverprofile=coverage ./...
